**Notebook roadmap (below):** load Moodify Excel → profile CIDs → call the same PubChem + parser stack as `bp_vp_construct.ipynb` → merge BP/VP onto every ingredient row → save CSV → print success-rate summary → **Part D:** merge `data/raw_dragon_matrix.csv`, build the same **54** standardized Dragon PCs as `features_set_1.ipynb` / `classifications_trials.ipynb` → rank by |Pearson r| vs boiling point → `X_top_df` / `X_top_arr` → Ridge regression and error metrics.

---

The idea is the follwing:
I do not have the full covering of "Waka" data set with experimental boiling point, 192 from 312. In ref.2 there is a claim that boiling point should be a good estimator for perceptual intncity. My idea is to use take single molecules list from the Moodify inventory ~2400 single molecules ingredients. Try to retrieve from pubchem Standard boiling point. Test the coverage, use Dragon-derived PC features (same pipeline as intensity classification), fit a regressor for boiling point, and inspect accuracy.

path to molecules data set with CID identifier project_1\data\Cannonical_names_for_moodify_db from pubchem.xlsx

In [7]:
# Libraries: pandas loads tables; pathlib builds paths that work on Windows/macOS/Linux.
from pathlib import Path

import pandas as pd

# Same pipeline as bp_vp_construct.ipynb:
#   batch_physical_props.fetch_props_for_dataframe
#     → pubchem_retriever2.get_pubchem_physical_props (PUG-View REST API)
#     → practical_parser2.parse_boiling_point (prefers normal BP near 760 mmHg → °C)
#     → practical_parser2.parse_vapor_pressure (prefers measurement near 25 °C → mmHg)
from batch_physical_props import fetch_props_for_dataframe, merge_props

DATA_DIR = Path("data")

In [8]:
# Reading .xlsx needs the `openpyxl` package in this kernel:  pip install openpyxl
xlsx_path = DATA_DIR / "Cannonical_names_for_moodify_db from pubchem.xlsx"
molecules_df = pd.read_excel(xlsx_path)
molecules_df.head()

,moodifyindex(mi),Name of Material,CAS,CID,SMILES,ConnectivitySMILES,InChI,InChIKey,IUPACName,retrieved_by
0,1000001,BENZALDEHYDE,100-52-7,240,C1=CC=C(C=C1)C=O,C1=CC=C(C=C1)C=O,InChI=1S/C7H6O/c8-6-7-4-2-1-3-5-7/h1-6H,HUMNYLRZRPPJDN-UHFFFAOYSA-N,benzaldehyde,CID
1,1000002,BOURGEONAL,18127-01-0,64832,CC(C)(C)C1=CC=C(C=C1)CCC=O,CC(C)(C)C1=CC=C(C=C1)CCC=O,"InChI=1S/C13H18O/c1-13(2,3)12-8-6-11(7-9-12)5-...",FZJUFJKVIYFBSY-UHFFFAOYSA-N,3-(4-tert-butylphenyl)propanal,CID
2,1000003,CAMPHOR,76-22-2,2537,CC1(C2CCC1(C(=O)C2)C)C,CC1(C2CCC1(C(=O)C2)C)C,"InChI=1S/C10H16O/c1-9(2)7-4-5-10(9,3)8(11)6-7/...",DSSYKIVIOFKYAU-UHFFFAOYSA-N,"1,7,7-trimethylbicyclo[2.2.1]heptan-2-one",CID
3,1000004,CEDROL METHYL ETHER,19870-74-7,88288,C[C@@H]1CC[C@@H]2[C@]13CC[C@]([C@H](C3)C2(C)C)...,CC1CCC2C13CCC(C(C3)C2(C)C)(C)OC,"InChI=1S/C16H28O/c1-11-6-7-12-14(2,3)13-10-16(...",HRGPYCVTDOECMG-WALBABNVSA-N,"(1S,2R,5S,7R,8S)-8-methoxy-2,6,6,8-tetramethyl...",CID
4,1000005,(E)-CITRAL,141-27-5,638011,CC(=CCC/C(=C/C=O)/C)C,CC(=CCCC(=CC=O)C)C,"InChI=1S/C10H16O/c1-9(2)5-4-6-10(3)7-8-11/h5,7...",WTEVQBCEXWBHNA-JXMROGBWSA-N,"(2E)-3,7-dimethylocta-2,6-dienal",CID

In [11]:
# Quick inventory: ingredient rows vs distinct PubChem CIDs.
# PubChem requests are one per *unique* CID; duplicate CIDs in this sheet are not re-fetched.
print("shape (rows, cols):", molecules_df.shape)
print("unique CID:", molecules_df["CID"].nunique())
print("rows with missing CID:", int(molecules_df["CID"].isna().sum()))

dup = molecules_df["CID"].value_counts()
print("CIDs used on more than one row:", int((dup > 1).sum()))

shape (rows, cols): (2326, 10)
unique CID: 2006
rows with missing CID: 0
CIDs used on more than one row: 242

### Step A — What PubChem gives us (same idea as `bp_vp_construct.ipynb`)

1. **Identifier** — We use **CID** (PubChem Compound ID). Your Moodify export already has it.

2. **Where the numbers come from** — `get_pubchem_physical_props` calls PubChem **PUG-View** for two section headings: *Boiling Point* and *Vapor Pressure*. The API returns free-text lines (often with units, pressures, temperatures).

3. **How we normalize ("standard-ish")** — `practical_parser2` turns that text into scalars:
   - **Boiling point** → degrees Celsius, preferring a value associated with **760 mmHg** (normal boiling point) when the text allows.
   - **Vapor pressure** → **mmHg**, preferring a measurement taken closest to **25 °C** (you can change `preferred_vp_temperature_c` if you need another reference temperature).

4. **Politeness & speed** — `delay_s` spaces requests so we do not hammer PubChem. **`resume=True`** appends each newly fetched CID to a **CSV cache**; if the run stops, the next run skips CIDs already stored.

5. **Shared cache** — We use the **same** `pubchem_physical_props_cache.csv` as the Waka notebook. Any CID already fetched there is reused **without** a new HTTP request. The `props_df` object you get back can therefore contain **more CIDs than Moodify** (it is the whole cache merged with this run); the summary cell later filters back to Moodify CIDs for compound-level percentages.

In [13]:
# Optional: show INFO lines from batch_physical_props (one line per newly fetched CID).
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

# This returns ONE ROW PER UNIQUE CID (not per ingredient row).
# First run for ~2300 new CIDs can take on the order of tens of minutes (delay + network).
props_df = fetch_props_for_dataframe(
    molecules_df,
    cid_column="CID",
    delay_s=0.35,
    max_retries=4,
    retry_backoff_s=2.0,
    preferred_vp_temperature_c=25.0,
    cache_path=DATA_DIR / "pubchem_physical_props_cache.csv",
    resume=True,
)

props_df.head()

INFO: Fetched CID 64832 (1 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 2537 (2 of 2006 unique CIDs this run): bp=203.889 vp=0.65 err=-
INFO: Fetched CID 88288 (3 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 86209 (4 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 641256 (5 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 443158 (6 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 5283335 (7 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 998 (8 of 2006 unique CIDs this run): bp=None vp=0.39 err=-
INFO: Fetched CID 637563 (9 of 2006 unique CIDs this run): bp=234.5 vp=0.05 err=-
INFO: Fetched CID 14286 (10 of 2006 unique CIDs this run): bp=191.0 vp=0.37 err=-
INFO: Fetched CID 122510 (11 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 26331 (12 of 2006 unique CIDs this run): bp=152.5 vp=1.67 err=-
INFO: Fetched CID 5371002 (13 of 2006 unique CIDs this run): bp=111.0 vp=None err=-
INFO: Fetched CID 999 (14 of 2006 unique CIDs this run): bp=215.0 vp=0.0038 err=-
INFO: Fetched CID 5374527 (15 of 2006 unique CIDs this run): bp=200.0 vp=None err=-
INFO: Fetched CID 62336 (16 of 2006 unique CIDs this run): bp=111.5 vp=None err=-
INFO: Fetched CID 93009 (17 of 2006 unique CIDs this run): bp=None vp=0.6 err=-
INFO: Fetched CID 11658397 (18 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 106729 (19 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7059 (20 of 2006 unique CIDs this run): bp=260.0 vp=3.0 err=-
INFO: Fetched CID 53422908 (21 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 3034278 (22 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7130 (23 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6437737 (24 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 111376 (25 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 10149036 (26 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6544 (27 of 2006 unique CIDs this run): bp=214.0 vp=0.438 err=-
INFO: Fetched CID 7460 (28 of 2006 unique CIDs this run): bp=None vp=1.4 err=-
INFO: Fetched CID 10890 (29 of 2006 unique CIDs this run): bp=186.0 vp=None err=-
INFO: Fetched CID 3034895 (30 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 106734 (31 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 11552 (32 of 2006 unique CIDs this run): bp=91.5 vp=50.0 err=-
INFO: Fetched CID 78435 (33 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 16220111 (34 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 61832 (35 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8347 (36 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 106756 (37 of 2006 unique CIDs this run): bp=112.5 vp=None err=-
INFO: Fetched CID 5355293 (38 of 2006 unique CIDs this run): bp=187.5 vp=None err=-
INFO: Fetched CID 3591866 (39 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6453284 (40 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 15984303 (41 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 539829 (42 of 2006 unique CIDs this run): bp=165.5 vp=None err=-
INFO: Fetched CID 1550884 (43 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6438196 (44 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 18955245 (45 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1742210 (46 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1550890 (47 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6437266 (48 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 9856149 (49 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 342 (50 of 2006 unique CIDs this run): bp=202.5 vp=0.11 err=-
INFO: Fetched CID 60997 (51 of 2006 unique CIDs this run): bp=310.0 vp=None err=-
INFO: Fetched CID 62002 (52 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 61014 (53 of 2006 unique CIDs this run): bp=140.0 vp=None err=-
INFO: Fetched CID 61945 (54 of 2006 unique CIDs this run): bp=107.5 vp=None err=-
INFO: Fetched CID 92030006 (55 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 43851 (56 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 105513 (57 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1213 (58 of 2006 unique CIDs this run): bp=270.5 vp=None err=-
INFO: Fetched CID 106826 (59 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 62332 (60 of 2006 unique CIDs this run): bp=370.0 vp=None err=-
INFO: Fetched CID 638014 (61 of 2006 unique CIDs this run): bp=267.5 vp=0.054 err=-
INFO: Fetched CID 8092 (62 of 2006 unique CIDs this run): bp=218.5 vp=None err=-
INFO: Fetched CID 175948 (63 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 114454 (64 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 22096564 (65 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 285097 (66 of 2006 unique CIDs this run): bp=135.0 vp=None err=-
INFO: Fetched CID 11367306 (67 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7984 (68 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 106766 (69 of 2006 unique CIDs this run): bp=214.5 vp=None err=-
INFO: Fetched CID 9834606 (70 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1136 (71 of 2006 unique CIDs this run): bp=135.0 vp=None err=-
INFO: Fetched CID 5971 (72 of 2006 unique CIDs this run): bp=151.0 vp=5.0 err=-
INFO: Fetched CID 2507689 (73 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 66327 (74 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 27941 (75 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 57495095 (76 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 57759198 (77 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 22201 (78 of 2006 unique CIDs this run): bp=156.0 vp=1.5 err=-
INFO: Fetched CID 61951 (79 of 2006 unique CIDs this run): bp=280.5 vp=None err=-
INFO: Fetched CID 7991 (80 of 2006 unique CIDs this run): bp=185.0 vp=0.196 err=-
INFO: Fetched CID 7519 (81 of 2006 unique CIDs this run): bp=154.0 vp=3.5253 err=-
INFO: Fetched CID 7966 (82 of 2006 unique CIDs this run): bp=161.111 vp=0.657 err=-
INFO: Fetched CID 90787 (83 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 15405344 (84 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 11332546 (85 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 21933618 (86 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8419 (87 of 2006 unique CIDs this run): bp=281.0 vp=None err=-
INFO: Fetched CID 62900 (88 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6441135 (89 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 94569 (90 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6441804 (91 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 11527 (92 of 2006 unique CIDs this run): bp=174.0 vp=None err=-
INFO: Fetched CID 41270 (93 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 61431 (94 of 2006 unique CIDs this run): bp=186.5 vp=None err=-
INFO: Fetched CID 16751505 (95 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 90818 (96 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 162309 (97 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 162053 (98 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 98403 (99 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 445070 (100 of 2006 unique CIDs this run): bp=283.5 vp=0.0 err=-
INFO: Fetched CID 3102 (101 of 2006 unique CIDs this run): bp=306.0 vp=1.0 err=-
INFO: Fetched CID 444539 (102 of 2006 unique CIDs this run): bp=299.0 vp=None err=-
INFO: Fetched CID 12020 (103 of 2006 unique CIDs this run): bp=114.0 vp=9.68 err=-
INFO: Fetched CID 1031 (104 of 2006 unique CIDs this run): bp=97.222 vp=21.0 err=-
INFO: Fetched CID 30914 (105 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 12741 (106 of 2006 unique CIDs this run): bp=210.0 vp=None err=-
INFO: Fetched CID 8051 (107 of 2006 unique CIDs this run): bp=149.5 vp=1.5001 err=-
INFO: Fetched CID 31252 (108 of 2006 unique CIDs this run): bp=155.0 vp=1.5 err=-
INFO: Fetched CID 12178 (109 of 2006 unique CIDs this run): bp=134.0 vp=4.81 err=-
INFO: Fetched CID 28500 (110 of 2006 unique CIDs this run): bp=173.889 vp=None err=-
INFO: Fetched CID 660 (111 of 2006 unique CIDs this run): bp=271.5 vp=13.4 err=-
INFO: Fetched CID 62465 (112 of 2006 unique CIDs this run): bp=235.5 vp=None err=-
INFO: Fetched CID 61138 (113 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 61199 (114 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 176 (115 of 2006 unique CIDs this run): bp=117.778 vp=15.7 err=-
INFO: Fetched CID 22833361 (116 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6654 (117 of 2006 unique CIDs this run): bp=156.0 vp=4.75 err=-
INFO: Fetched CID 263 (118 of 2006 unique CIDs this run): bp=117.722 vp=7.0 err=-
INFO: Fetched CID 264 (119 of 2006 unique CIDs this run): bp=163.5 vp=1.65 err=-
INFO: Fetched CID 534634 (120 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 440917 (121 of 2006 unique CIDs this run): bp=175.833 vp=1.98 err=-
INFO: Fetched CID 31249 (122 of 2006 unique CIDs this run): bp=217.5 vp=0.9976 err=-
INFO: Fetched CID 1030 (123 of 2006 unique CIDs this run): bp=188.222 vp=0.13 err=-
INFO: Fetched CID 11980 (124 of 2006 unique CIDs this run): bp=196.8 vp=None err=-
INFO: Fetched CID 7742 (125 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8094 (126 of 2006 unique CIDs this run): bp=222.5 vp=0.0107 err=-
INFO: Fetched CID 8892 (127 of 2006 unique CIDs this run): bp=202.5 vp=0.2025 err=-
INFO: Fetched CID 22873 (128 of 2006 unique CIDs this run): bp=245.5 vp=None err=-
INFO: Fetched CID 6374 (129 of 2006 unique CIDs this run): bp=217.778 vp=0.04 err=-
INFO: Fetched CID 8042 (130 of 2006 unique CIDs this run): bp=315.0 vp=0.0001 err=-
INFO: Fetched CID 7600 (131 of 2006 unique CIDs this run): bp=268.0 vp=None err=-
INFO: Fetched CID 6590 (132 of 2006 unique CIDs this run): bp=153.5 vp=1.81 err=-
INFO: Fetched CID 3776 (133 of 2006 unique CIDs this run): bp=82.3 vp=45.4 err=-
INFO: Fetched CID 10430 (134 of 2006 unique CIDs this run): bp=176.0 vp=0.44 err=-
INFO: Fetched CID 7793 (135 of 2006 unique CIDs this run): bp=225.0 vp=None err=-
INFO: Fetched CID 18635 (136 of 2006 unique CIDs this run): bp=62.0 vp=0.397 err=-
INFO: Fetched CID 9862 (137 of 2006 unique CIDs this run): bp=72.5 vp=0.75 err=-
INFO: Fetched CID 8091 (138 of 2006 unique CIDs this run): bp=194.5 vp=None err=-
INFO: Fetched CID 7559 (139 of 2006 unique CIDs this run): bp=216.0 vp=0.13 err=-
INFO: Fetched CID 8918 (140 of 2006 unique CIDs this run): bp=212.0 vp=None err=-
INFO: Fetched CID 7194 (141 of 2006 unique CIDs this run): bp=189.0 vp=None err=-
INFO: Fetched CID 1049 (142 of 2006 unique CIDs this run): bp=115.5 vp=20.8 err=-
INFO: Fetched CID 11230 (143 of 2006 unique CIDs this run): bp=89.0 vp=None err=-
INFO: Fetched CID 6989 (144 of 2006 unique CIDs this run): bp=231.5 vp=0.016 err=-
INFO: Fetched CID 6506 (145 of 2006 unique CIDs this run): bp=294.0 vp=0.0022 err=-
INFO: Fetched CID 443162 (146 of 2006 unique CIDs this run): bp=80.75 vp=0.05 err=-
INFO: Fetched CID 13006 (147 of 2006 unique CIDs this run): bp=194.0 vp=None err=-
INFO: Fetched CID 1045 (148 of 2006 unique CIDs this run): bp=158.5 vp=4.12 err=-
INFO: Fetched CID 273 (149 of 2006 unique CIDs this run): bp=179.0 vp=1.01 err=-
INFO: Fetched CID 5634 (150 of 2006 unique CIDs this run): bp=275.0 vp=None err=-
INFO: Fetched CID 18522 (151 of 2006 unique CIDs this run): bp=138.5 vp=None err=-
INFO: Fetched CID 11509 (152 of 2006 unique CIDs this run): bp=123.5 vp=13.9 err=-
INFO: Fetched CID 42011 (153 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 31211 (154 of 2006 unique CIDs this run): bp=187.5 vp=None err=-
INFO: Fetched CID 102579 (155 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 66349 (156 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 26204 (157 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 66678 (158 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1550846 (159 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 5365794 (160 of 2006 unique CIDs this run): bp=None vp=30.7 err=-
INFO: Fetched CID 3033030 (161 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 459494 (162 of 2006 unique CIDs this run): bp=142.5 vp=None err=-
INFO: Fetched CID 6999980 (163 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8148 (164 of 2006 unique CIDs this run): bp=159.444 vp=2.59 err=-
INFO: Fetched CID 1103 (165 of 2006 unique CIDs this run): bp=150.0 vp=None err=-
INFO: Fetched CID 7580 (166 of 2006 unique CIDs this run): bp=264.5 vp=0.0082 err=-
INFO: Fetched CID 25484 (167 of 2006 unique CIDs this run): bp=184.0 vp=0.4 err=-
INFO: Fetched CID 10024 (168 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 10821 (169 of 2006 unique CIDs this run): bp=142.0 vp=17.6 err=-
INFO: Fetched CID 98478 (170 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7362 (171 of 2006 unique CIDs this run): bp=161.5 vp=1.1251 err=-
INFO: Fetched CID 93847 (172 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 71552 (173 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 984 (174 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 93111 (175 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6873 (176 of 2006 unique CIDs this run): bp=261.0 vp=None err=-
INFO: Fetched CID 67285 (177 of 2006 unique CIDs this run): bp=None vp=0.01 err=-
INFO: Fetched CID 161676 (178 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 78484 (179 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8181 (180 of 2006 unique CIDs this run): bp=417.0 vp=0.0001 err=-
INFO: Fetched CID 106917 (181 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 5371125 (182 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7685 (183 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 76334 (184 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 17697 (185 of 2006 unique CIDs this run): bp=285.0 vp=None err=-
INFO: Fetched CID 62433 (186 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 31236 (187 of 2006 unique CIDs this run): bp=237.5 vp=0.007 err=-
INFO: Fetched CID 11030204 (188 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 92821 (189 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 543323 (190 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 5463791 (191 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1127 (192 of 2006 unique CIDs this run): bp=121.12 vp=18.0015 err=-
INFO: Fetched CID 1140 (193 of 2006 unique CIDs this run): bp=110.5 vp=28.5024 err=-
INFO: Fetched CID 109245 (194 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 6850756 (195 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 929262 (196 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 19309 (197 of 2006 unique CIDs this run): bp=216.0 vp=0.008 err=-
INFO: Fetched CID 5317570 (198 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 10453 (199 of 2006 unique CIDs this run): bp=108.5 vp=0.0 err=-
INFO: Fetched CID 641423 (200 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 62375 (201 of 2006 unique CIDs this run): bp=88.0 vp=None err=-
INFO: Fetched CID 31283 (202 of 2006 unique CIDs this run): bp=179.0 vp=None err=-
INFO: Fetched CID 7657 (203 of 2006 unique CIDs this run): bp=296.5 vp=0.001 err=-
INFO: Fetched CID 9016 (204 of 2006 unique CIDs this run): bp=211.5 vp=0.08 err=-
INFO: Fetched CID 444972 (205 of 2006 unique CIDs this run): bp=200.0 vp=0.0002 err=-
INFO: Fetched CID 2969 (206 of 2006 unique CIDs this run): bp=269.0 vp=0.0004 err=-
INFO: Fetched CID 60999 (207 of 2006 unique CIDs this run): bp=319.0 vp=None err=-
INFO: Fetched CID 5365049 (208 of 2006 unique CIDs this run): bp=181.0 vp=None err=-
INFO: Fetched CID 24197 (209 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 9025 (210 of 2006 unique CIDs this run): bp=86.0 vp=0.52 err=-
INFO: Fetched CID 16255 (211 of 2006 unique CIDs this run): bp=267.5 vp=None err=-
INFO: Fetched CID 126 (212 of 2006 unique CIDs this run): bp=310.5 vp=None err=-
INFO: Fetched CID 66823518 (213 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 243 (214 of 2006 unique CIDs this run): bp=249.2 vp=0.0008 err=-
INFO: Fetched CID 61670 (215 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7761 (216 of 2006 unique CIDs this run): bp=199.5 vp=0.27 err=-
INFO: Fetched CID 61252 (217 of 2006 unique CIDs this run): bp=175.0 vp=None err=-
INFO: Fetched CID 994 (218 of 2006 unique CIDs this run): bp=None vp=0.0 err=-
INFO: Fetched CID 62374 (219 of 2006 unique CIDs this run): bp=93.0 vp=None err=-
INFO: Fetched CID 116736 (220 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 61024 (221 of 2006 unique CIDs this run): bp=237.0 vp=None err=-
INFO: Fetched CID 875 (222 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 1550470 (223 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 15654 (224 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 7593 (225 of 2006 unique CIDs this run): bp=330.5 vp=None err=-
INFO: Fetched CID 15717 (226 of 2006 unique CIDs this run): bp=239.5 vp=None err=-
INFO: Fetched CID 239 (227 of 2006 unique CIDs this run): bp=None vp=0.0 err=-
INFO: Fetched CID 8049 (228 of 2006 unique CIDs this run): bp=303.5 vp=None err=-
INFO: Fetched CID 7768 (229 of 2006 unique CIDs this run): bp=266.889 vp=0.0019 err=-
INFO: Fetched CID 9012 (230 of 2006 unique CIDs this run): bp=270.0 vp=None err=-
INFO: Fetched CID 196 (231 of 2006 unique CIDs this run): bp=337.5 vp=0.0 err=-
INFO: Fetched CID 165675 (232 of 2006 unique CIDs this run): bp=216.111 vp=1.0 err=-
INFO: Fetched CID 14296 (233 of 2006 unique CIDs this run): bp=190.0 vp=None err=-
INFO: Fetched CID 145742 (234 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 15606 (235 of 2006 unique CIDs this run): bp=213.5 vp=0.21 err=-
INFO: Fetched CID 8658 (236 of 2006 unique CIDs this run): bp=238.0 vp=0.12 err=-
INFO: Fetched CID 15037 (237 of 2006 unique CIDs this run): bp=78.0 vp=None err=-
INFO: Fetched CID 520108 (238 of 2006 unique CIDs this run): bp=90.0 vp=None err=-
INFO: Fetched CID 62346 (239 of 2006 unique CIDs this run): bp=None vp=None err=-
INFO: Fetched CID 8815 (240 of 2006 unique CIDs this run): bp=215.5 vp=0.05 err=-
INFO: Fetched CID 23235 (241 of 2006 unique CIDs this run): bp=272.0 vp=32.0 err=-
INFO: Fetched CID 24834 (242 of 2006 unique CIDs this run): bp=249.5 vp=None err=-

   cid  boiling_point_c  vapor_pressure_mmhg error
0  107          280.000                  NaN
1  125          252.000               0.0008
2  126          310.500                  NaN
3  176          117.778              15.7000
4  177           21.111             902.0000

### Step B — Merge properties back onto every ingredient row

`props_df` is compact (unique CIDs). The Moodify table has **one row per ingredient**; several rows can share one CID.

`merge_props` **left-joins** the parsed columns onto `molecules_df` on `CID`, so every ingredient keeps its own row and gets the BP/VP for its compound. New columns:
- `bp_c_pubchem` — boiling point (°C)
- `vp_mmhg_pubchem` — vapor pressure (mmHg) near 25 °C when the parser could extract it
- `bp_c_pubchem_fetch_error` — non-empty if the HTTP/retry layer failed (not the same as "PubChem has no BP text")

In [14]:
molecules_with_props = merge_props(
    molecules_df,
    props_df,
    cid_column="CID",
    bp_column="bp_c_pubchem",
    vp_column="vp_mmhg_pubchem",
)

out_path = DATA_DIR / "moodify_inventory_pubchem_bp_vp.csv"
molecules_with_props.to_csv(out_path, index=False)
print("Wrote:", out_path.resolve())
molecules_with_props.head()

Wrote: C:\src\ai-program-2026\project_1\data\moodify_inventory_pubchem_bp_vp.csv

,moodifyindex(mi),Name of Material,CAS,CID,SMILES,ConnectivitySMILES,InChI,InChIKey,IUPACName,retrieved_by,bp_c_pubchem,vp_mmhg_pubchem,bp_c_pubchem_fetch_error
0,1000001,BENZALDEHYDE,100-52-7,240,C1=CC=C(C=C1)C=O,C1=CC=C(C=C1)C=O,InChI=1S/C7H6O/c8-6-7-4-2-1-3-5-7/h1-6H,HUMNYLRZRPPJDN-UHFFFAOYSA-N,benzaldehyde,CID,178.889,1.27,NaN
1,1000002,BOURGEONAL,18127-01-0,64832,CC(C)(C)C1=CC=C(C=C1)CCC=O,CC(C)(C)C1=CC=C(C=C1)CCC=O,"InChI=1S/C13H18O/c1-13(2,3)12-8-6-11(7-9-12)5-...",FZJUFJKVIYFBSY-UHFFFAOYSA-N,3-(4-tert-butylphenyl)propanal,CID,NaN,NaN,
2,1000003,CAMPHOR,76-22-2,2537,CC1(C2CCC1(C(=O)C2)C)C,CC1(C2CCC1(C(=O)C2)C)C,"InChI=1S/C10H16O/c1-9(2)7-4-5-10(9,3)8(11)6-7/...",DSSYKIVIOFKYAU-UHFFFAOYSA-N,"1,7,7-trimethylbicyclo[2.2.1]heptan-2-one",CID,203.889,0.65,
3,1000004,CEDROL METHYL ETHER,19870-74-7,88288,C[C@@H]1CC[C@@H]2[C@]13CC[C@]([C@H](C3)C2(C)C)...,CC1CCC2C13CCC(C(C3)C2(C)C)(C)OC,"InChI=1S/C16H28O/c1-11-6-7-12-14(2,3)13-10-16(...",HRGPYCVTDOECMG-WALBABNVSA-N,"(1S,2R,5S,7R,8S)-8-methoxy-2,6,6,8-tetramethyl...",CID,NaN,NaN,
4,1000005,(E)-CITRAL,141-27-5,638011,CC(=CCC/C(=C/C=O)/C)C,CC(=CCCC(=CC=O)C)C,"InChI=1S/C10H16O/c1-9(2)5-4-6-10(3)7-8-11/h5,7...",WTEVQBCEXWBHNA-JXMROGBWSA-N,"(2E)-3,7-dimethylocta-2,6-dienal",CID,228.500,1.00,NaN

In [ ]:
*(Optional)* Run **Step C** summary cell above first; **Part D** starts in the next cells.

### Step C — Success rates (how to read them)

- **Fetch layer** — `error` in `props_df` (shown as `bp_c_pubchem_fetch_error` on the merged table) means the script could not complete a parseable download after retries. Rare if the network behaves.

- **Coverage** — A **successful fetch** can still yield `NaN` for BP or VP if PubChem has no usable text for that field, or the parser could not extract a number.

We report: (1) **per unique CID** — what fraction of compounds have values; (2) **per ingredient row** — same but weighted by your table (duplicate CIDs count multiple times).

In [15]:
# `props_df` can include CIDs from earlier projects (shared CSV cache). For Moodify-only
# compound-level rates, restrict to CIDs that appear in the ingredient table.
_m = molecules_df["CID"].dropna()
moodify_cid_set = set(int(float(x)) for x in _m.unique())
props_moodify = props_df.loc[props_df["cid"].isin(moodify_cid_set)].copy()

err_merged = molecules_with_props["bp_c_pubchem_fetch_error"].fillna("")
err_props_m = props_moodify["error"].fillna("")

n_moodify_cids = len(moodify_cid_set)
n_props_rows_for_moodify = int(props_moodify["cid"].nunique())

summary = {
    # --- Ingredient-level (merged rows) ---
    "n_ingredient_rows": len(molecules_with_props),
    "rows_with_missing_cid": int(molecules_with_props["CID"].isna().sum()),
    "rows_bp_present_pct": round(molecules_with_props["bp_c_pubchem"].notna().mean() * 100, 2),
    "rows_vp_present_pct": round(molecules_with_props["vp_mmhg_pubchem"].notna().mean() * 100, 2),
    "rows_both_bp_and_vp_pct": round(
        (molecules_with_props["bp_c_pubchem"].notna() & molecules_with_props["vp_mmhg_pubchem"].notna()).mean()
        * 100,
        2,
    ),
    "rows_fetch_error_pct": round((err_merged != "").mean() * 100, 2),
    # --- Moodify compound-level (unique CIDs in this Excel, subset of props_df) ---
    "moodify_distinct_cids": n_moodify_cids,
    "moodify_cids_with_a_props_row": n_props_rows_for_moodify,
    "moodify_cids_still_missing_from_props_after_fetch": n_moodify_cids - n_props_rows_for_moodify,
    "moodify_cids_bp_present_pct": round(props_moodify["boiling_point_c"].notna().mean() * 100, 2)
    if n_props_rows_for_moodify
    else None,
    "moodify_cids_vp_present_pct": round(props_moodify["vapor_pressure_mmhg"].notna().mean() * 100, 2)
    if n_props_rows_for_moodify
    else None,
    "moodify_cids_both_bp_and_vp_pct": round(
        (props_moodify["boiling_point_c"].notna() & props_moodify["vapor_pressure_mmhg"].notna()).mean() * 100,
        2,
    )
    if n_props_rows_for_moodify
    else None,
    "moodify_cids_fetch_error_pct": round((err_props_m != "").mean() * 100, 2)
    if n_props_rows_for_moodify
    else None,
}

import json

print(json.dumps(summary, indent=2))

{
  "n_ingredient_rows": 2326,
  "rows_with_missing_cid": 0,
  "rows_bp_present_pct": 52.45,
  "rows_vp_present_pct": 25.75,
  "rows_both_bp_and_vp_pct": 23.34,
  "rows_fetch_error_pct": 0.0,
  "moodify_distinct_cids": 2006,
  "moodify_cids_with_a_props_row": 2006,
  "moodify_cids_still_missing_from_props_after_fetch": 0,
  "moodify_cids_bp_present_pct": 50.9,
  "moodify_cids_vp_present_pct": 23.28,
  "moodify_cids_both_bp_and_vp_pct": 21.19,
  "moodify_cids_fetch_error_pct": 0.0
}